"""remove unique constraint

Revision ID: cd6dd729be79
Revises: a1fa7d0c3e07
Create Date: 2026-03-06 23:47:13.850105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd6dd729be79'
down_revision: Union[str, Sequence[str], None] = 'a1fa7d0c3e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_page_page_url'), table_name='page')
    op.alter_column('provider', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('setting_category', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.create_unique_constraint(op.f('uq_site_site_url'), 'site', ['site_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_site_site_url'), 'site', type_='unique')
    op.alter_column('setting_category', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('provider', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.create_index(op.f('uq_page_page_url'), 'page', ['page_url'], unique=False)
    op.create_table('test_case_credentials',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('page_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('placeholder_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('value', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_page_placeholder'), 'test_case_credentials', ['page_id', 'placeholder_key'], unique=True)
    op.create_index(op.f('ix_test_case_credentials_page_id'), 'test_case_credentials', ['page_id'], unique=False)
    # ### end Alembic commands ###
